"""empty message

Revision ID: 3668c82f6740
Revises: 3e9a465edc4d
Create Date: 2016-02-13 22:38:57.177366

"""

# revision identifiers, used by Alembic.
revision = '3668c82f6740'
down_revision = '3e9a465edc4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('attachurls', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'attachurls')
    ### end Alembic commands ###
