"""empty message

Revision ID: 38288b17f781
Revises: 48771005612b
Create Date: 2016-01-24 09:58:10.186218

"""

# revision identifiers, used by Alembic.
revision = '38288b17f781'
down_revision = '48771005612b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiatives', sa.Column('name', sa.String(length=20), nullable=True))
    op.create_index('ix_initiatives_name', 'initiatives', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_initiatives_name', 'initiatives')
    op.drop_column('initiatives', 'name')
    ### end Alembic commands ###
