"""empty message

Revision ID: 48771005612b
Revises: c626e32ddcc
Create Date: 2016-01-24 09:25:42.092490

"""

# revision identifiers, used by Alembic.
revision = '48771005612b'
down_revision = 'c626e32ddcc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initiatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_initiatives_timestamp', 'initiatives', ['timestamp'], unique=False)
    op.create_table('updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('initiative_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_updates_timestamp', 'updates', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_updates_timestamp', 'updates')
    op.drop_table('updates')
    op.drop_index('ix_initiatives_timestamp', 'initiatives')
    op.drop_table('initiatives')
    ### end Alembic commands ###
