"""empty message

Revision ID: 867adbff51e
Revises: 38288b17f781
Create Date: 2016-02-06 10:46:48.670093

"""

# revision identifiers, used by Alembic.
revision = '867adbff51e'
down_revision = '38288b17f781'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(length=24), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'category')
    ### end Alembic commands ###
